# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Diffdecoding < Formula
  desc ""
  homepage "https://github.com/meoconbatu/homebrew-tools"
  version "1.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meoconbatu/diffdecoding/releases/download/1.1.1/diffdecoding_1.1.1_Darwin_x86_64.tar.gz"
      sha256 "993fa0e354e43beb96d7dd6a87d597f4e056e9bdba494a1d88b2e34e86ac2379"

      def install
        bin.install "diffdecoding"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meoconbatu/diffdecoding/releases/download/1.1.1/diffdecoding_1.1.1_Darwin_arm64.tar.gz"
      sha256 "2465d7dc35200164b81d9562b6ec41919a757103ddd8d5b0c40d422865f7cc1a"

      def install
        bin.install "diffdecoding"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meoconbatu/diffdecoding/releases/download/1.1.1/diffdecoding_1.1.1_Linux_arm64.tar.gz"
      sha256 "fdf427e243d10ae2e775583d1952d0d3b7d8d929b11e24e2fb5b516a87f247e7"

      def install
        bin.install "diffdecoding"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/meoconbatu/diffdecoding/releases/download/1.1.1/diffdecoding_1.1.1_Linux_x86_64.tar.gz"
      sha256 "eb541f28607a7379439312e7c55be8a9bfadb68bf83204d4c31a5ce23697f558"

      def install
        bin.install "diffdecoding"
      end
    end
  end
end
