# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Diffdecoding < Formula
  desc ""
  homepage "https://github.com/meoconbatu/homebrew-tools"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/meoconbatu/diffdecoding/releases/download/v1.0.0/diffdecoding_1.0.0_Darwin_arm64.tar.gz"
      sha256 "b4a51cd751cd986d186e05146180a006fcd061e9fd07dc28b0fbed37610064b5"

      def install
        bin.install "diffdecoding"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/meoconbatu/diffdecoding/releases/download/v1.0.0/diffdecoding_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "66cddff83140a2c62d2bb5c66bb592418cb94c83f41b5b491700a40850d58919"

      def install
        bin.install "diffdecoding"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/meoconbatu/diffdecoding/releases/download/v1.0.0/diffdecoding_1.0.0_Linux_x86_64.tar.gz"
      sha256 "98decb46987ed32c89d76ba5db984e88098bfd0ef7d4e7c88449a7d37921dc37"

      def install
        bin.install "diffdecoding"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meoconbatu/diffdecoding/releases/download/v1.0.0/diffdecoding_1.0.0_Linux_arm64.tar.gz"
      sha256 "dc38d2a59ba708d256c7694e839752e825a92ea607c5b273dd266bd5df82fbcc"

      def install
        bin.install "diffdecoding"
      end
    end
  end
end
